repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: .venv/bin/ruff check --fix
        language: system
        types: [python]
        pass_filenames: true

      - id: ruff-format
        name: ruff-format
        entry: .venv/bin/ruff format
        language: system
        types: [python]
        pass_filenames: true

      - id: mypy
        name: mypy
        entry: .venv/bin/mypy
        language: system
        types: [python]
        pass_filenames: false
        args: [--config-file=pyproject.toml, agent, bot]

      - id: bandit
        name: bandit
        entry: .venv/bin/python -m bandit
        language: system
        types: [python]
        args: [-lll, -q, --exclude, .venv,tests]
        pass_filenames: false
